services:
  database:
    container_name: database
    image: postgres:17
    environment:
      # set up database using database user credential from env file
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      # initialize database with scripts from ./database/init
      - ./database/init:/docker-entrypoint-initdb.d:ro
      # persist database data in ./database/data
      - ${POSTGRES_DB_PERSISTENCE_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_OWNER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  database-client:
    container_name: database-client
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=True
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      # persist database-client state
      - ${PGADMIN_PERSISTENCE_VOLUME}:/var/lib/pgadmin
    depends_on:
      - database

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

  backend:
    build: ./backend
    container_name: backend
    environment:
      # postgres database variables
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_DB_HOST=database
      - POSTGRES_DB_PORT=${POSTGRES_DB_PORT}
      # redis cache variables
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      # index logic variables
      - INDEX_BASE_VALUE=${INDEX_BASE_VALUE}
      - TOTAL_NUMBER_OF_INDEX_CONSTITUENTS=${TOTAL_NUMBER_OF_INDEX_CONSTITUENTS}
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
