services:
  database:
    container_name: database
    image: postgres:17
    environment:
      # set up database using database owner credential from env file
      - POSTGRES_USER=${POSTGRES_DB_OWNER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_OWNER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      # initialize database with scripts from ./database/init
      - ./database/init:/docker-entrypoint-initdb.d:ro
      # persist database data in ./database/data
      - ./database/data/server:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_DB_OWNER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  database-client:
    container_name: database-client
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=True
    ports:
      - "5050:80"
    volumes:
      # persist database-client state
      - ./database/data/client:/var/lib/pgadmin
    depends_on:
      - database

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

#  backend:
#    build: ./backend
#    container_name: backend
#    ports:
#      - "8000:8000"
#    depends_on:
#      - database
#      - redis
